# Generated by Django 4.0.5 on 2022-07-06 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attempt',
            name='end_time',
        ),
    ]
