# Generated by Django 4.0.5 on 2022-07-06 01:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0002_remove_attempt_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
