# Generated by Django 4.0.5 on 2022-07-06 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0004_alter_attempt_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
